In [1]:
"Hello"

'Hello'

In [50]:
import pandas as pd
import numpy as np
import requests
import json

In [20]:
base__url = "https://restcountries.com/v3.1/currency/cop"
base__url

'https://restcountries.com/v3.1/currency/cop'

In [21]:
response = requests.get(base__url)
response.status_code

200

In [27]:
data = response.json()
print(json.dumps(data, indent=2))

[
  {
    "name": {
      "common": "Colombia",
      "official": "Republic of Colombia",
      "nativeName": {
        "spa": {
          "official": "Rep\u00fablica de Colombia",
          "common": "Colombia"
        }
      }
    },
    "tld": [
      ".co"
    ],
    "cca2": "CO",
    "ccn3": "170",
    "cca3": "COL",
    "cioc": "COL",
    "independent": true,
    "status": "officially-assigned",
    "unMember": true,
    "currencies": {
      "COP": {
        "name": "Colombian peso",
        "symbol": "$"
      }
    },
    "idd": {
      "root": "+5",
      "suffixes": [
        "7"
      ]
    },
    "capital": [
      "Bogot\u00e1"
    ],
    "altSpellings": [
      "CO",
      "Republic of Colombia",
      "Rep\u00fablica de Colombia"
    ],
    "region": "Americas",
    "subregion": "South America",
    "languages": {
      "spa": "Spanish"
    },
    "translations": {
      "ara": {
        "official": "\u062c\u0645\u0647\u0648\u0631\u064a\u0629 \u0643\u0648\u0644\u0648\u

In [41]:
base__url2 = base__url + "/history" +"?start_Date = 12-12-2003&end_Date=04-04-2010"
base__url2

'https://restcountries.com/v3.1/currency/cop/history?start_Date = 12-12-2003&end_Date=04-04-2010'

In [42]:
response = requests.get(base__url2)
response.status_code # This 404 indicates error doesnot exist

404

In [43]:
data = response.json()

In [45]:
print(json.dumps(data, indent = 4, sort_keys=True))

{
    "_links": {
        "self": {
            "href": "/v3.1/currency/cop/history?start_Date%20=%2012-12-2003&end_Date=04-04-2010",
            "templated": false
        }
    },
    "message": "Page Not Found"
}


In [46]:
response.json()

{'message': 'Page Not Found',
 '_links': {'self': {'href': '/v3.1/currency/cop/history?start_Date%20=%2012-12-2003&end_Date=04-04-2010',
   'templated': False}}}

In [ ]:
# Build a calculator and take user input
# Gathering the paramters of interst
# construct the url and send a get request to it
# for unsuccessful request : print the error message
# for successful reuest : retrive the relevent data and calculate the result

# take 4 input arguments from the user:

date = input("Please input date (mm-dd-yyyy):")
base_curr = input("Please input base currency: ")
target_curr = input("Please input target currency: " )
quan_curr = float(input("Please input quantity to convert: ".formator(base)))


url = base_url + "/"+date+"?base-"+base_curr+"&symbols-"+curr
response = requests.get(url)



In [ ]:
# Search API:


In [49]:
url = "https://itunes.apple.com/search"
url

'https://itunes.apple.com/search'

In [69]:
response = requests.get(url, params={
    "term": " the beatles", "country": "us"
})
response.status_code
response.url

'https://itunes.apple.com/search?term=+the+beatles&country=us'

In [70]:
data = response.json()
print(json.dumps(data, indent = 4 ))

{
    "resultCount": 52,
    "results": [
        {
            "wrapperType": "audiobook",
            "artistId": 160778930,
            "collectionId": 1439484338,
            "artistName": "Bob Spitz",
            "collectionName": "The Beatles (Abridged)",
            "collectionCensoredName": "The Beatles (Abridged)",
            "artistViewUrl": "https://books.apple.com/us/author/bob-spitz/id160778930?uo=4",
            "collectionViewUrl": "https://books.apple.com/us/audiobook/the-beatles-abridged/id1439484338?uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/69/b8/65/69b86591-ce4b-9bd0-ab71-3808d0ea06dc/9780743552455.jpg/60x60bb.jpg",
            "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/69/b8/65/69b86591-ce4b-9bd0-ab71-3808d0ea06dc/9780743552455.jpg/100x100bb.jpg",
            "collectionPrice": 19.99,
            "collectionExplicitness": "cleaned",
            "trackCount": 1,
            "country": "USA",


In [72]:
data.keys()

dict_keys(['resultCount', 'results'])

In [74]:
print(json.dumps(data['results'][9], indent = 4))

{
    "wrapperType": "track",
    "kind": "song",
    "artistId": 136975,
    "collectionId": 1441133180,
    "trackId": 1441133834,
    "artistName": "The Beatles",
    "collectionName": "The Beatles (The White Album)",
    "trackName": "Blackbird",
    "collectionCensoredName": "The Beatles (The White Album)",
    "trackCensoredName": "Blackbird",
    "artistViewUrl": "https://music.apple.com/us/artist/the-beatles/136975?uo=4",
    "collectionViewUrl": "https://music.apple.com/us/album/blackbird/1441133180?i=1441133834&uo=4",
    "trackViewUrl": "https://music.apple.com/us/album/blackbird/1441133180?i=1441133834&uo=4",
    "previewUrl": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/81/92/53/81925382-68ea-cee8-2f91-f824ac1dc455/mzaf_8008503031387003585.plus.aac.p.m4a",
    "artworkUrl30": "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/fa/5b/89/fa5b898d-bad6-e053-4195-260e5c74f2bb/00602567725466.rgb.jpg/30x30bb.jpg",
    "artworkUrl60": "https://is1-ssl.mz

In [76]:
print(json.dumps(data['results'][2]))


{"wrapperType": "track", "kind": "song", "artistId": 157458, "collectionId": 282495289, "trackId": 282495296, "artistName": "Daniel Johnston", "collectionName": "Yip! Jump Music", "trackName": "The Beatles", "collectionCensoredName": "Yip! Jump Music", "trackCensoredName": "The Beatles", "artistViewUrl": "https://music.apple.com/us/artist/daniel-johnston/157458?uo=4", "collectionViewUrl": "https://music.apple.com/us/album/the-beatles/282495289?i=282495296&uo=4", "trackViewUrl": "https://music.apple.com/us/album/the-beatles/282495289?i=282495296&uo=4", "previewUrl": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/e6/81/31/e68131e4-2889-d027-d1e2-6755e56fd434/mzaf_13627254640725098082.plus.aac.p.m4a", "artworkUrl30": "https://is1-ssl.mzstatic.com/image/thumb/Music/c7/24/19/mzi.hsrvxuky.jpg/30x30bb.jpg", "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Music/c7/24/19/mzi.hsrvxuky.jpg/60x60bb.jpg", "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Mus

In [86]:
r = requests.get(url, params ={
    'media' : 'hahahahaha', ' count' : '2321'
})
r.status_code
r.json()

{'errorMessage': 'Invalid value(s) for key(s): [mediaType]',
 'queryParameters': {'output': 'json',
  'callback': 'A javascript function to handle your search results',
  'country': 'ISO-2A country code',
  'limit': 'The number of search results to return',
  'term': 'A search string',
  'lang': 'ISO-2A language code'}}

In [94]:
print(json.dumps(data['results'][1:3], indent = 4))

[
    {
        "wrapperType": "audiobook",
        "artistId": 2037074,
        "collectionId": 1646008816,
        "artistName": "Hunter Davies",
        "collectionName": "The Beatles",
        "collectionCensoredName": "The Beatles",
        "artistViewUrl": "https://books.apple.com/us/author/hunter-davies/id2037074?uo=4",
        "collectionViewUrl": "https://books.apple.com/us/audiobook/the-beatles/id1646008816?uo=4",
        "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/a9/d4/1d/a9d41dc7-12e1-c377-71fe-019d4d5116d2/2350-square.jpg/60x60bb.jpg",
        "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/a9/d4/1d/a9d41dc7-12e1-c377-71fe-019d4d5116d2/2350-square.jpg/100x100bb.jpg",
        "collectionPrice": 19.99,
        "collectionExplicitness": "cleaned",
        "trackCount": 1,
        "copyright": "\u00a9 1998 by Blackstone Audio, Inc.",
        "country": "USA",
        "currency": "USD",
        "releaseDate": "1999-02-01T08:00:0

In [103]:
pd.DataFrame(data['results']).size

2288

In [105]:
pd.DataFrame(data['results']).dropna().size # no missing rows

0

In [107]:
pd.DataFrame(data['results'][0:10]).loc

In [1]:
# .toexcel("")
# .tocsv("")

# pagination:
# I've learn how to pull data using get request.
# 

In [1]:
# Data frame is two dimensional
import pandas as pd
import numpy as np

# numpy array 2 x 3 array/ matrix
array_a = np.array([[2,3,4], [45,66,7]])
array_a

array([[ 2,  3,  4],
       [45, 66,  7]])

In [2]:
# duilding it into a pandas library
a = pd.DataFrame(array_a, columns=['Column 1', 'Column 2', 'Column 3'],
                index = ['Row 1', 'Row 2'])
a

Column 1  Column 2  Column 3
Row 1         2         3         4
Row 2        45        66         7

In [3]:
type(a)

pandas.core.frame.DataFrame

In [4]:
data = pd.read_csv('college.csv', sep=',')
data

school Private  Accept.pct  Elite10  \
0       Abilene Christian University     Yes    0.742169        0   
1                 Adelphi University     Yes    0.880146        0   
2                     Adrian College     Yes    0.768207        0   
3                Agnes Scott College     Yes    0.836930        1   
4          Alaska Pacific University     Yes    0.756477        0   
..                               ...     ...         ...      ...   
726                  Wofford College     Yes    0.622918        1   
727  Worcester Polytechnic Institute     Yes    0.835983        0   
728          Worcester State College      No    0.689577        0   
729                Xavier University     Yes    0.921388        0   
730   Xavier University of Louisiana     Yes    0.913209        0   

     F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  \
0           2885          537      7440        3300    450      2200   70   
1           2683         1227     12280        6450    750      1500   29   
2           1036           99     11250        3750    400      1165   53   
3            510           63     12960        5450    450       875   92   
4            249          869      7560        4120    800      1500   76   
..           ...          ...       ...         ...    ...       ...  ...   
726         1059           34     12680        4150    605      1440   91   
727         2802           86     15884        5370    530       730   92   
728         3089         2029      6797        3900    500      1200   60   
729         2849         1107     11520        4960    600      1250   73   
730         2793          166      6900        4200    617       781   67   

     Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0          78       18.1           12    7041         60  
1          30       12.2           16   10527         56  
2          66       12.9           30    8735         54  
3          97        7.7           37   19016         59  
4          72       11.9            2   10922         15  
..        ...        ...          ...     ...        ...  
726        92       15.3           42    7875         75  
727        94       15.2           34   10774         82  
728        60       21.0           14    4469         40  
729        75       13.3           31    9189         83  
730        75       14.4           20    8323         49  

[731 rows x 16 columns]

In [5]:
data1 = pd.DataFrame(data.loc[:, ['school', 'Private']])
data1

school Private
0       Abilene Christian University     Yes
1                 Adelphi University     Yes
2                     Adrian College     Yes
3                Agnes Scott College     Yes
4          Alaska Pacific University     Yes
..                               ...     ...
726                  Wofford College     Yes
727  Worcester Polytechnic Institute     Yes
728          Worcester State College      No
729                Xavier University     Yes
730   Xavier University of Louisiana     Yes

[731 rows x 2 columns]

In [6]:
data1.isna().sum().sort_values(ascending = True).head(10)

school     0
Private    0
dtype: int64

In [7]:
data.columns


Index(['school', 'Private', 'Accept.pct', 'Elite10', 'F.Undergrad',
       'P.Undergrad', 'Outstate', 'Room.Board', 'Books', 'Personal', 'PhD',
       'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend', 'Grad.Rate'],
      dtype='object')

In [8]:
# shape method shows the dimensionality of the data
data.shape # 731 rows and 16 columns

(731, 16)

In [9]:
len(data)

731

In [10]:
len(data.columns)

16

In [11]:
# how to index each element in a data frame is very crucial
# And keeping track of  data consistency is the major goal of data analysis


# Data of a specific column
pd.DataFrame(data['school'])

school
0       Abilene Christian University
1                 Adelphi University
2                     Adrian College
3                Agnes Scott College
4          Alaska Pacific University
..                               ...
726                  Wofford College
727  Worcester Polytechnic Institute
728          Worcester State College
729                Xavier University
730   Xavier University of Louisiana

[731 rows x 1 columns]

In [12]:
pd.DataFrame(data[['school', 'Private']]).tail(20)

school Private
711           Westminster College PA     Yes
712          Wheeling Jesuit College     Yes
713                  Whitman College     Yes
714                 Whittier College     Yes
715                Whitworth College     Yes
716               Widener University     Yes
717                Wilkes University     Yes
718            Willamette University     Yes
719           William Jewell College     Yes
720                 Williams College     Yes
721                   Wilson College     Yes
722          Winona State University      No
723              Winthrop University      No
724       Wisconsin Lutheran College     Yes
725            Wittenberg University     Yes
726                  Wofford College     Yes
727  Worcester Polytechnic Institute     Yes
728          Worcester State College      No
729                Xavier University     Yes
730   Xavier University of Louisiana     Yes

In [13]:
data[['school', 'Private']]

school Private
0       Abilene Christian University     Yes
1                 Adelphi University     Yes
2                     Adrian College     Yes
3                Agnes Scott College     Yes
4          Alaska Pacific University     Yes
..                               ...     ...
726                  Wofford College     Yes
727  Worcester Polytechnic Institute     Yes
728          Worcester State College      No
729                Xavier University     Yes
730   Xavier University of Louisiana     Yes

[731 rows x 2 columns]

In [14]:
locao = ['school', 'Private'] # Professionals prefer this approach
pd.DataFrame(data[locao]).head(7)

school Private
0  Abilene Christian University     Yes
1            Adelphi University     Yes
2                Adrian College     Yes
3           Agnes Scott College     Yes
4     Alaska Pacific University     Yes
5             Albertson College     Yes
6       Albertus Magnus College     Yes

In [15]:
# iloc indexing for qualitative columns
# attribute indexing ()
# iloc(int location)
# integer location / position based indexing


data.iloc[7,1] # this will fecth 7th rows and first column


'Yes'

In [16]:
data.iloc[:, 0]

0         Abilene Christian University
1                   Adelphi University
2                       Adrian College
3                  Agnes Scott College
4            Alaska Pacific University
                    ...               
726                    Wofford College
727    Worcester Polytechnic Institute
728            Worcester State College
729                  Xavier University
730     Xavier University of Louisiana
Name: school, Length: 731, dtype: object

In [17]:
data.iloc[:, :]

school Private  Accept.pct  Elite10  \
0       Abilene Christian University     Yes    0.742169        0   
1                 Adelphi University     Yes    0.880146        0   
2                     Adrian College     Yes    0.768207        0   
3                Agnes Scott College     Yes    0.836930        1   
4          Alaska Pacific University     Yes    0.756477        0   
..                               ...     ...         ...      ...   
726                  Wofford College     Yes    0.622918        1   
727  Worcester Polytechnic Institute     Yes    0.835983        0   
728          Worcester State College      No    0.689577        0   
729                Xavier University     Yes    0.921388        0   
730   Xavier University of Louisiana     Yes    0.913209        0   

     F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  \
0           2885          537      7440        3300    450      2200   70   
1           2683         1227     12280        6450    750      1500   29   
2           1036           99     11250        3750    400      1165   53   
3            510           63     12960        5450    450       875   92   
4            249          869      7560        4120    800      1500   76   
..           ...          ...       ...         ...    ...       ...  ...   
726         1059           34     12680        4150    605      1440   91   
727         2802           86     15884        5370    530       730   92   
728         3089         2029      6797        3900    500      1200   60   
729         2849         1107     11520        4960    600      1250   73   
730         2793          166      6900        4200    617       781   67   

     Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0          78       18.1           12    7041         60  
1          30       12.2           16   10527         56  
2          66       12.9           30    8735         54  
3          97        7.7           37   19016         59  
4          72       11.9            2   10922         15  
..        ...        ...          ...     ...        ...  
726        92       15.3           42    7875         75  
727        94       15.2           34   10774         82  
728        60       21.0           14    4469         40  
729        75       13.3           31    9189         83  
730        75       14.4           20    8323         49  

[731 rows x 16 columns]

In [18]:
type(data.iloc[1,9]) 

numpy.int64

In [19]:
pd.DataFrame(data.iloc[1, :]) # retrive only 2'nd row's details
# iloc(int  location): this is used to position based indexing or int indexing
# to retrive the column and row of interest
# and ype function retrive the type fucntion of this object


1
school       Adelphi University
Private                     Yes
Accept.pct             0.880146
Elite10                       0
F.Undergrad                2683
P.Undergrad                1227
Outstate                  12280
Room.Board                 6450
Books                       750
Personal                   1500
PhD                          29
Terminal                     30
S.F.Ratio                  12.2
perc.alumni                  16
Expend                    10527
Grad.Rate                    56

In [20]:
data.iloc[:, [3,1]] # allowed to change the order of the list

Elite10 Private
0          0     Yes
1          0     Yes
2          0     Yes
3          1     Yes
4          0     Yes
..       ...     ...
726        1     Yes
727        0     Yes
728        0      No
729        0     Yes
730        0     Yes

[731 rows x 2 columns]

In [21]:
# loc method is used to retrive info ththrough labels
# main differnece between iloc and loc
# we did not assign indexing at this data set hence
# below code is not functioning
#data.loc['Adelphi University', :]    


In [22]:
# explicit index: loc indexer or loc accessor
# this is used by referring to index labels

data.loc[0:2]

school Private  Accept.pct  Elite10  F.Undergrad  \
0  Abilene Christian University     Yes    0.742169        0         2885   
1            Adelphi University     Yes    0.880146        0         2683   
2                Adrian College     Yes    0.768207        0         1036   

   P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0          537      7440        3300    450      2200   70        78   
1         1227     12280        6450    750      1500   29        30   
2           99     11250        3750    400      1165   53        66   

   S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0       18.1           12    7041         60  
1       12.2           16   10527         56  
2       12.9           30    8735         54

In [23]:
data.loc[:, 'Private'] 

0      Yes
1      Yes
2      Yes
3      Yes
4      Yes
      ... 
726    Yes
727    Yes
728     No
729    Yes
730    Yes
Name: Private, Length: 731, dtype: object

In [24]:
data.loc[1, 'Private'] # perfect indication of explicit labeling
# remember this is a series and not paranthesis


'Yes'

In [25]:
data = pd.read_csv('college.csv', index_col='school')
data

Private  Accept.pct  Elite10  F.Undergrad  \
school                                                                      
Abilene Christian University        Yes    0.742169        0         2885   
Adelphi University                  Yes    0.880146        0         2683   
Adrian College                      Yes    0.768207        0         1036   
Agnes Scott College                 Yes    0.836930        1          510   
Alaska Pacific University           Yes    0.756477        0          249   
...                                 ...         ...      ...          ...   
Wofford College                     Yes    0.622918        1         1059   
Worcester Polytechnic Institute     Yes    0.835983        0         2802   
Worcester State College              No    0.689577        0         3089   
Xavier University                   Yes    0.921388        0         2849   
Xavier University of Louisiana      Yes    0.913209        0         2793   

                                 P.Undergrad  Outstate  Room.Board  Books  \
school                                                                      
Abilene Christian University             537      7440        3300    450   
Adelphi University                      1227     12280        6450    750   
Adrian College                            99     11250        3750    400   
Agnes Scott College                       63     12960        5450    450   
Alaska Pacific University                869      7560        4120    800   
...                                      ...       ...         ...    ...   
Wofford College                           34     12680        4150    605   
Worcester Polytechnic Institute           86     15884        5370    530   
Worcester State College                 2029      6797        3900    500   
Xavier University                       1107     11520        4960    600   
Xavier University of Louisiana           166      6900        4200    617   

                                 Personal  PhD  Terminal  S.F.Ratio  \
school                                                                
Abilene Christian University         2200   70        78       18.1   
Adelphi University                   1500   29        30       12.2   
Adrian College                       1165   53        66       12.9   
Agnes Scott College                   875   92        97        7.7   
Alaska Pacific University            1500   76        72       11.9   
...                                   ...  ...       ...        ...   
Wofford College                      1440   91        92       15.3   
Worcester Polytechnic Institute       730   92        94       15.2   
Worcester State College              1200   60        60       21.0   
Xavier University                    1250   73        75       13.3   
Xavier University of Louisiana        781   67        75       14.4   

                                 perc.alumni  Expend  Grad.Rate  
school                                                           
Abilene Christian University              12    7041         60  
Adelphi University                        16   10527         56  
Adrian College                            30    8735         54  
Agnes Scott College                       37   19016         59  
Alaska Pacific University                  2   10922         15  
...                                      ...     ...        ...  
Wofford College                           42    7875         75  
Worcester Polytechnic Institute           34   10774         82  
Worcester State College                   14    4469         40  
Xavier University                         31    9189         83  
Xavier University of Louisiana            20    8323         49  

[731 rows x 15 columns]

In [26]:
# to apply loc method which means index labeling
data.loc['Alaska Pacific University', :]

Private             Yes
Accept.pct     0.756477
Elite10               0
F.Undergrad         249
P.Undergrad         869
Outstate           7560
Room.Board         4120
Books               800
Personal           1500
PhD                  76
Terminal             72
S.F.Ratio          11.9
perc.alumni           2
Expend            10922
Grad.Rate            15
Name: Alaska Pacific University, dtype: object

In [27]:
data.loc['Alaska Pacific University', 'Private']

'Yes'

In [28]:
data.loc[['Alaska Pacific University', 'Wofford College'], :]

Private  Accept.pct  Elite10  F.Undergrad  \
school                                                                
Alaska Pacific University     Yes    0.756477        0          249   
Wofford College               Yes    0.622918        1         1059   

                           P.Undergrad  Outstate  Room.Board  Books  Personal  \
school                                                                          
Alaska Pacific University          869      7560        4120    800      1500   
Wofford College                     34     12680        4150    605      1440   

                           PhD  Terminal  S.F.Ratio  perc.alumni  Expend  \
school                                                                     
Alaska Pacific University   76        72       11.9            2   10922   
Wofford College             91        92       15.3           42    7875   

                           Grad.Rate  
school                                
Alaska Pacific University         15  
Wofford College                   75

In [29]:
data.loc[['Alaska Pacific University', 'Wofford College'], ['Outstate', 'Private']]

Outstate Private
school                                     
Alaska Pacific University      7560     Yes
Wofford College               12680     Yes

In [30]:
array_a = np.array([[2,3,4], [3,4,5]])
array_a

array([[2, 3, 4],
       [3, 4, 5]])

In [31]:
array_a[0]

array([2, 3, 4])

In [32]:
array_a[1]

array([3, 4, 5])

In [33]:
r = pd.DataFrame(array_a,columns=['Col1 ', 'Col2', 'Col3'],
                index=['row1', 'row2'])
r

Col1   Col2  Col3
row1      2     3     4
row2      3     4     5

In [34]:
r.loc['row1', :]

Col1     2
Col2     3
Col3     4
Name: row1, dtype: int32

In [35]:
r.loc['row2', 'Col3']

5

In [36]:
array_a

array([[2, 3, 4],
       [3, 4, 5]])

In [37]:
array_a[0][2] # implcitly acces 4

4

In [38]:
r.iloc[:, [1,2]] # slicing technique

Col2  Col3
row1     3     4
row2     4     5

In [39]:
array_a.shape

(2, 3)

In [40]:
len(array_a)

2

In [41]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [42]:
array_a[-1]

array([3, 4, 5])

In [43]:
# Assigning Values:
array_a

array([[2, 3, 4],
       [3, 4, 5]])

In [44]:
array_a[0][2] = 3

In [45]:
array_a

array([[2, 3, 3],
       [3, 4, 5]])

In [46]:
array_a[0]=0 # assigning all elements at o index 
array_a

array([[0, 0, 0],
       [3, 4, 5]])

In [47]:
array_a[:][1] = 9
array_a

array([[0, 0, 0],
       [9, 9, 9]])

In [48]:
array_a[:] =10
array_a

array([[10, 10, 10],
       [10, 10, 10]])

In [50]:
array_a +2

array([[12, 12, 12],
       [12, 12, 12]])

In [51]:
array_a

array([[10, 10, 10],
       [10, 10, 10]])

In [52]:
array_a-2

array([[8, 8, 8],
       [8, 8, 8]])

In [54]:
list1 = [1,2,3]
list1+[2]

[1, 2, 3, 2]

In [55]:
array_a + array_b+[2]

array([[13, 14, 15],
       [13, 14, 15]])

In [56]:
array_a

array([[10, 10, 10],
       [10, 10, 10]])

In [57]:
array_b

array([1, 2, 3])

In [58]:
array_b - array_a

array([[-9, -8, -7],
       [-9, -8, -7]])

In [60]:
array_a-array_b # order is always important (don't forget)

array([[9, 8, 7],
       [9, 8, 7]])

In [61]:
# the different data types numpy can support
# how changing the type of data affect in how we see the data it stores
array_a = np.array([[3,4,5], [2,3,4]])

In [62]:
array_a

array([[3, 4, 5],
       [2, 3, 4]])

In [67]:
# dataset to be of specific kind
array_a = np.array([[3,4,5,2], [455,3,2,2]], dtype = "float32")

In [68]:
array_a

array([[  3.,   4.,   5.,   2.],
       [455.,   3.,   2.,   2.]], dtype=float32)

In [65]:
array_a = np.array([[3,4,5,2], [455,3,2,2]], dtype = "complex64")

In [72]:
array_a = np.array([[3,4,5,2], [455,3,2,2]], dtype = "int32")
array_a

array([[  3,   4,   5,   2],
       [455,   3,   2,   2]])

In [74]:
array_a = np.array([[3,4,5,2], [455,3,2,2]], dtype = np.int32)
array_a

array([[  3,   4,   5,   2],
       [455,   3,   2,   2]])

In [76]:
array_a = np.array([[3,4,5,2], [455,3,2,2]], dtype = np.float64)
array_a

array([[  3.,   4.,   5.,   2.],
       [455.,   3.,   2.,   2.]])

In [77]:
# how numpy works with complex numbers:
# real + img part
array_a = np.array([[3,4,5,2], [455,3,2,2]], dtype = np.complex64)
array_a

array([[  3.+0.j,   4.+0.j,   5.+0.j,   2.+0.j],
       [455.+0.j,   3.+0.j,   2.+0.j,   2.+0.j]], dtype=complex64)

In [79]:
array_a = np.array([[3,4,5,2], [455,3,2,2]], dtype = np.bool_)
array_a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [80]:
array_a = np.array([[3,4,5,2], [455,3,2,2]], dtype = np.str_)
array_a # different sub types of strings

array([['3', '4', '5', '2'],
       ['455', '3', '2', '2']], dtype='<U3')

In [82]:
# Fundamentals of Numpy Functions:
# Type Chasting: Taking every element of an array
# and changing it to a specified datatype

# Attribute chaining and method chaining (Two important concepts)



# Let's practice Type Casting:
array_1 = ([[3,4,4], [765,4,5]])
array_2 = ([[3,2,3], [4,2,4]])

# this will convert all elements into float and then add them up

np.add(array_1, array_2, dtype = np.float32)

array([[  6.,   6.,   7.],
       [769.,   6.,   9.]], dtype=float32)

In [84]:
# Substentially it thorws an error becaue it will convert all elements
# first into strng and then adds them up

#np.add(array_1, array_2, dtype = np.str_)

In [85]:
# Running function along an axis
a=2<<2 
print(a)

8
